### ISSUE TITLE
FlareSolverr was unable to process the request, please check FlareSolverr logs (6+ providers)

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [FlareSolverr/FlareSolverr#100]
### Environment

**FlareSolverr Version**: version":"v1.2.3

**Docker**: [no] - using macos launchctl to run it (from source)

**OS**:  macOS

**Last Working FlareSolverr Version**: N/A

**Are you using a proxy or VPN?** [no]

**Using Captcha Solver:** [no]

**If using captcha solver, which one:**

### Description

just run test via jacket

![Screen Shot 2021-03-19 at 4 27 44 am](https://user-images.githubusercontent.com/2242880/111670958-88543e80-886c-11eb-800d-666bd92ee8cd.jpg)

### Logged Error Messages

Full Log with Debugging HTML etc..
[FlareSolverr.log](https://github.com/FlareSolverr/FlareSolverr/files/6166138/FlareSolverr.log)
[FlareSolverr-error.log](https://github.com/FlareSolverr/FlareSolverr/files/6166170/FlareSolverr-error.log)

note same issues with `hcaptcha-solver` set

**Comment by ngosang** [comment]
There are 2 different issues:
* Captcha detected but no automatic solver ... => This can't be fixed at this moment but only few sites have captcha. You should use other sites.
* Timeout error => This issue is temporal most of the time. It's caused by DDoS to the site and we can't fix that. Just try again after a while.

Jackett supports +500 sites and FlareSolverr is not able to make all work. This is a best effort project.
