### ISSUE TITLE
[torrentleech] (updating) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

### ISSUE THREAD

**Issue by petercontact** [FlareSolverr/FlareSolverr#1386]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Have you ACTUALLY checked all these?

YES

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:v3.3.21
- Operating system: windows 10
- Are you using Docker: no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no]
- Are you using a Proxy: no]
- Are you using Captcha Solver: no]
- If using captcha solver, which one:
- URL to test this issue:https://www.torrentleech.cc/user/account/login/
```

### Description

I got this message when i try to configure torrentleech, i updated FlareSolverr with no luck 

### Logged Error Messages

```text
2024-10-12 13:11:11 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://www.torrentleech.cc/user/account/login/'}
2024-10-12 13:11:15 INFO     Challenge detected. Title found: Just a moment...
2024-10-12 13:12:10 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
2024-10-12 13:12:10 INFO     Response in 58.999 s
2024-10-12 13:12:10 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 500 Internal Server Error
```

**Comment by Barborica-Alexandru** [comment]
Yes I am also experiencing this issue. It would seem that the checkbox is not being detected by flaresolvrr. What I don't understand is why I can't manually press on it. I normally run headless on docker on my linux machine and decided to run flaresolvrr on windows to see what the issue is, I ran with headless false and I can see the checkbox, I click on it, and then it it says verified and then the checkbox appears again and it just loops over and over again. In the console it reports that no checkbox was detected even though I see it and press on it. It would seem that this is a bug.
