### ISSUE TITLE
Outbound Proxy Support

### ISSUE THREAD

**Issue by dadcoachengineer** [FlareSolverr/FlareSolverr#300]
Looked in the issues here and reddit and did not see anything similar.

Does flaresolverr support outbound proxy support? Any docker ENV to send all outbound traffic through a web proxy?

Thanks!

**Comment by jscoys** [comment]
Hello guys, any news on that? Flaresolverr is now supporting proxy, can you expose a variable, like CAPTCHA_SOLVER, so we can put the url in it please?

**Comment by ngosang** [comment]
Outbound proxy is supported but you have to include it in each request. https://github.com/FlareSolverr/FlareSolverr#-requestget

I didn't include the Environment Variable for the proxy because I think it can cause troubles when using Jackett or other apps. If the proxy configuration is different in the apps the cookies won't work.
