### ISSUE TITLE
Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException

### ISSUE THREAD

**Issue by Feifei4256** [FlareSolverr/FlareSolverr#408]
### Environment

* **FlareSolverr version**:
* **Last working FlareSolverr version**:
* **Operating system**:
* **Are you using Docker**: [yes]
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** [no]
* **Are you using Captcha Solver:** [yes/no]
* **If using captcha solver, which one:**
* **URL to test this issue:**

[Place any screenshots of the issue here if needed]
![image](https://user-images.githubusercontent.com/102518894/173517970-e537f2dd-172d-402f-bc70-d3f3bf20340c.png)

**Comment by ilike2burnthing** [comment]
The rest of the requested information is also needed.

Are you able to access the FlareSolverr API URL in browser? If so, what is the response?

**Comment by eejag** [comment]
I've just had a similar error. Turns out after a jackett update to v0.20.1251 (not sure if it's related or due to another update in the system), the API port for Flaresolverr changed from 8237 to 8220.
I've changed the API port in the jackett Configuration and now the error is gone.

On the other hand i have now another issue with YGG tracker (possibly unrelated):
Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: No challenge selectors found, unable to proceed.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: No challenge selectors found, unable to proceed.

So.. Don't know if solved the initial issue or just created a new one :|
