### ISSUE TITLE
Use a pool of browsers instead of an instance at every request

### ISSUE THREAD

**Issue by M-Boukhlouf** [FlareSolverr/FlareSolverr#6]
This is just a suggestion. Instead of starting a new instance of the browser, have a pool of browsers. So if all the browsers of the pool are busy when a request comes, it will have to wait until one of them becomes free.

**Comment by NoahCardoza** [comment]
If you take a look at this [issue](https://github.com/ngosang/FlareSolverr/issues/4), you can check out my fork where I added "session" IDs to each browser instance. From there, you'd be able to control your own pool on your side.

The only problem with the pool that I can see, is that if you want to clear the cookies there'd need to be some way to reset one of the browsers in the pool. However, if you used all the browsers for the same website that might not be a problem.

I do think the pool is a good idea because it would also decrease the time spent on the first request. With my `session` modification, it takes about `3s` for the first request to start up the browser, and all following requests to that session only take `300-500ms` which is pretty fast. I'm not sure how it would vary if you wanted to make a lot of requests though.

**Comment by ngosang** [comment]
FlareSolverr 1.2.0 is out!
This feature is included.
Installation => https://github.com/FlareSolverr/FlareSolverr#docker
