### ISSUE TITLE
[yggcookie] (testing) Exception (yggcookie): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: NS_ERROR_CONNECTION_REFUSED at https://www5.yggtorrent.fi/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: NS_ERROR_CONNECTION_REFUSED at https://www5.yggtorrent.fi/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date

### ISSUE THREAD

**Issue by Sonicboum** [FlareSolverr/FlareSolverr#601]
### Environment

* **FlareSolverr version**: 2.2.10
* **Last working FlareSolverr version**:2.2.6
* **Operating system**:Syno
* **Are you using Docker**: [yes]
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** [yes]
* **Are you using Captcha Solver:** [I don't know]
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

All working well so far The error indicate means everything and nothing... I searched but I found nothing

### Logged Error Messages

[yggcookie] (testing) Exception (yggcookie): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: NS_ERROR_CONNECTION_REFUSED at https://www5.yggtorrent.fi/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: NS_ERROR_CONNECTION_REFUSED at https://www5.yggtorrent.fi/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date

**Comment by ilike2burnthing** [comment]
Try without the proxy.

**Comment by Sonicboum** [comment]
In Jackett there is no proxy enable

**Comment by ilike2burnthing** [comment]
> **Are you using a proxy or VPN?** [yes]

What was that referring to?

**Comment by Sonicboum** [comment]
> Essayez sans le proxy.

I was referring to your post.
My jacket is working normally and I got this error

**Comment by Sonicboum** [comment]
Oh, I use cyberghost.
If I remove my VPN a new error appears.
My server is in France and Ygg is not accessible from France, so I use a VPN...

**Comment by Sonicboum** [comment]
Exception (yggcookie): Cannot assign requested address: Cannot assign requested address (www5.yggtorrent.fi:443)

**Comment by ilike2burnthing** [comment]
Are both the Jackett and FlareSolverr containers using the VPN?

Are other indexers working? Do any of them use FlareSolverr?

**Comment by Sonicboum** [comment]
They are both on the same machine, so I think they are both using the vpn.
All other indexers work, but I don't have any other indexer that uses FlareSolverr only this one.

**Comment by ilike2burnthing** [comment]
Add `Badass Torrents` and perform a search for `720p`, that should trigger a Cloudflare check.

**Comment by lborruto** [comment]
Same issue since yesterday for me:

`2022-11-24T09:24:41+00:00 INFO FlareSolverr v2.2.10
2022-11-24T09:24:41+00:00 INFO Testing web browser installation...
2022-11-24T09:24:44+00:00 INFO FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
2022-11-24T09:24:44+00:00 INFO Test successful
2022-11-24T09:24:44+00:00 INFO Listening on http://0.0.0.0:8191
2022-11-24T09:25:44+00:00 INFO REQ-1 Incoming request => POST /v1 body: {"maxTimeout":55000,"cmd":"request.get","url":"https://www5.yggtorrent.fi/"}
2022-11-24T09:25:47+00:00 INFO REQ-1 Cloudflare detected
2022-11-24T09:26:41+00:00 ERROR REQ-1 Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=55000 (ms)
2022-11-24T09:26:41+00:00 INFO REQ-1 Response in 57.09 s
2022-11-24T09:26:41+00:00 ERROR REQ-1 Unexpected error: Error: Protocol error (Network.getCookies): Session closed. Most likely the page has been closed.
2022-11-24T09:26:58+00:00 INFO REQ-2 Incoming request => POST /v1 body: {"maxTimeout":55000,"cmd":"request.get","url":"https://www5.yggtorrent.fi/"}
2022-11-24T09:27:01+00:00 INFO REQ-2 Cloudflare detected
2022-11-24T09:27:56+00:00 INFO REQ-2 Response in 57.402 s
2022-11-24T09:27:56+00:00 ERROR REQ-2 Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=55000 (ms)
2022-11-24T09:27:56+00:00 ERROR REQ-2 Unexpected error: Error: Protocol error (Network.getCookies): Session closed. Most likely the page has been closed.`

`[yggtorrent] (updating) Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 55 seconds elapsing. ---> System.TimeoutException: The operation was canceled. ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException (125): Operation canceled   --- End of inner exception stack trace ---   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)   --- End of inner exception stack trace ---   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)   --- End of inner exception stack trace ---   ---`

**Comment by Sonicboum** [comment]
Badass Torrents Doesn't Use Flaresolverr...
I tried with and without Flarevolser it doesn't change anything.

**Comment by ilike2burnthing** [comment]
It doesn't when using the `Test` function or a keywordless search - https://badasstorrents.com/torrents

But it does (or at least does for me) when performing a keyword search, e.g. `720p`. Does it not for you?

**Comment by Sonicboum** [comment]
I just did several tests and in all cases badasstorrents does not use Flaresolver.
Flaresolver console does not show a request....

**Comment by Sonicboum** [comment]
I wonder if it does not come from the DNS of my server.

**Comment by lborruto** [comment]
Duplicate issue: https://github.com/FlareSolverr/FlareSolverr/issues/596

        On Yggtorrent forum, they say Flaresolverr blocked RSS flux to prevent DDoS attacks, the issue should be solved in a few days.

_Originally posted by @Ekks-O in https://github.com/FlareSolverr/FlareSolverr/issues/596#issuecomment-1326074025_

**Comment by ilike2burnthing** [comment]
Odd. Ok, try BT4G, Idope, Torrent[CORE], or TorrentQQ then.

@lborruto it's a different error, but thanks.

**Comment by lborruto** [comment]
> Odd. Ok, try BT4G, Idope, Torrent[CORE], or TorrentQQ then.
> 
> @lborruto it's a different error, but thanks.

It's not the same error, but we all have the same issue with YGG and it's all related to the RSS flux being blocked.

**Comment by ilike2burnthing** [comment]
If it's a different error, then you most likely don't have the same issue.

Also, Jackett doesn't use the RSS feed from YGG, and therefore it has nothing to do with https://github.com/FlareSolverr/FlareSolverr/issues/596. It seems the explanation given by the YGG mods has been misunderstood; they were talking about 2 different things in the linked thread.

**Comment by Sonicboum** [comment]
J'ai essayer avec les autres indexer que vous m'avez conseillé et j'ai le meme problème...
My Flaresolverr is up to date and I reinstalled it to be sure

**Comment by ilike2burnthing** [comment]
Did they give the same error when you weren't using your VPN?

**Comment by Sonicboum** [comment]
When I'm not using the VPN I get this error:

Exception (yggcookie): Cannot assign requested address: Cannot assign requested address (www5.yggtorrent.fi:443)

When I use it I get this:

FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: NS_ERROR_CONNECTION_REFUSED at https://www5.yggtorrent.fi/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: NS_ERROR_CONNECTION_REFUSED at https://www5.yggtorrent.fi/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date

**Comment by ilike2burnthing** [comment]
For the other indexers.

**Comment by Sonicboum** [comment]
It doesn't change anything...

When I'm not using the VPN I get this error:

Exception (bt4g): Cannot assign requested address: Cannot assign requested address (bt4g.org:443)

When I use it I get this:

FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: NS_ERROR_CONNECTION_REFUSED at https://bt4g.org/search/2022: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: NS_ERROR_CONNECTION_REFUSED at https://bt4g.org/search/2022

**Comment by ilike2burnthing** [comment]
Are you able to access those 4 sites in browser without a VPN?

Are you using a particular DNS (e.g. Google or Cloudflare) on your computer? Are you also using this DNS for the Jackett and FlareSolverr containers?

**Comment by Sonicboum** [comment]
In France the sites are for the most part not accessible...
I use the vpn so that the sites are accessible, I do not use DNS I think I should maybe configure some...

**Comment by Sonicboum** [comment]
I tried to configure the DNS but did not change... Knowing that above all it worked perfectly...

**Comment by TurboMachina** [comment]
Also here : yggtorrent broken. From flaresolverr logs :

`
[yggtorrent] (updating) Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 55 seconds elapsing. ---> System.TimeoutException: The operation was canceled. ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException (125): Operation canceled   --- End of inner exception stack trace ---   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)   --- End of inner exception stack trace ---   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)   --- End of inner exception stack trace ---   ---
`
And from docker logs command : 

`
2022-11-25T15:13:00+01:00 ERROR REQ-9 Unexpected error: Error: Protocol error (Network.getCookies): Session closed. Most likely the page has been closed.
2022-11-25T15:13:12+01:00 INFO REQ-10 Incoming request => POST /v1 body: {"maxTimeout":55000,"cmd":"request.get","url":"https://www5.yggtorrent.fi/"}
2022-11-25T15:13:15+01:00 INFO REQ-10 Cloudflare detected
2022-11-25T15:14:09+01:00 ERROR REQ-10 Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=55000 (ms)
2022-11-25T15:14:09+01:00 INFO REQ-10 Response in 57.165 s
`

From Germany, it was working perfectly fine until 2 days ago, not using a VPN, version v2.2.10 on Debian 11 x64

**Comment by ilike2burnthing** [comment]
@TurboMachina different issue - https://github.com/FlareSolverr/FlareSolverr/issues/596

**Comment by ilike2burnthing** [comment]
@Sonicboum what are you using as the FlareSolverr API URL in Jackett?

**Comment by Sonicboum** [comment]
I have docker installed on the same machine, it is responsible for launching Flaresolver.
So I use the ip of the machine (ex: 192.168.0.120:9191) with the appropriate port.
When I type the link in my browser it returns me a complete request with version and confirmation message that Flaresolver is working well.

**Comment by ilike2burnthing** [comment]
Use the internal Docker container IP instead, e.g. `http://172.17.0.2:8191`, or container name if configured, e.g. `http://flaresolverr:8191`.

**Comment by Sonicboum** [comment]
I tested your alternatives and it changed the error.
In fact, he can't connect to Flaresolverr with the ips...

Exception (bt4g): Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Name or service not known (flaresolverr:8191) ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.H

**Comment by ilike2burnthing** [comment]
Those were examples, hence the use of `e.g.`.

You would need to get your container's actual internal IP, and presumably you haven't configured a container name (or at least it wasn't `flaresolverr`).

**Comment by Sonicboum** [comment]
I'm sorry, I understood the meaning of what you told me.
What I wanted to tell you is that in the case where I put flaresolver:port does not work but when I put the ip of the container it works.
But I still get the same error...

I don't think the problem comes from the connection between jackett and flaresolverr...

Exception (bt4g): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: NS_ERROR_CONNECTION_REFUSED at https://bt4g.org/search/2022: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: NS_ERROR_CONNECTION_REFUSED at https://bt4g.org/search/2022

**Comment by ilike2burnthing** [comment]
Please provide the FlareSolverr log for this.

**Comment by Sonicboum** [comment]
Here are the Flaresolverr logs

https://pastebin.com/i0hTz72F

**Comment by ilike2burnthing** [comment]
Try switching to the v3 beta, see if that resolves the issue with the VPN - https://github.com/FlareSolverr/FlareSolverr/issues/522

**Comment by Sonicboum** [comment]
> Essayez de passer à la version bêta v3, voyez si cela résout le problème avec le VPN - #522

Here is the answer !
Thank you very much
