### ISSUE TITLE
Increase timeout ?

### ISSUE THREAD

**Issue by chicungunya** [FlareSolverr/FlareSolverr#62]
Hi,
I use an old Raspberry Pi 3 and max time out is 60s. And everytime I have errror.
Is that possible to increase this in my container ?

Thanks a lot

**Comment by ngosang** [comment]
If you are using Jackett it's not possible to increase the timeout. It's hardcoded in Jackett because there are other timeouts and changing this timeout can cause other issues really difficult to debug.
If you are using FlareSolverr directly you can configure the timeout in the request. See the readme.

Are you sure the issue is the timeout? I guess is a memory issue that can't be fixed changing the timeout. 
Enable debug logs and share the traces: https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace

**Comment by ngosang** [comment]
I'm going to make configurable global default timeout in the next release. But this is not going to solve the timeout in Jackett since Jackett overwrites the timeout.

**Comment by ngosang** [comment]
I changed my mind. I think there is no need for another environment variable.
