### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

### ISSUE THREAD

**Issue by Phantomouf** [FlareSolverr/FlareSolverr#693]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3
- Last working FlareSolverr version:3
- Operating system:Debian 10
- Are you using Docker: [yes/no] no
- FlareSolverr User-Agent (see log traces or / endpoint):i don't know where is it
- Are you using a VPN: [yes/no]no
- Are you using a Proxy: [yes/no]no
- Are you using Captcha Solver: [yes/no]no
- If using captcha solver, which one:
- URL to test this issue:https://91.121.222.191:8206
```

### Description

i'm using QuickBox pro

### Logged Error Messages

```text
dont know where is it
```

**Comment by ilike2burnthing** [comment]
If you're using Jackett/Prowlarr and FlareSolverr on the same device and the same IP (i.e. no VPN or proxy), with IPv6 disabled, and other indexers which require FlareSolverr are working (TorrentQQ is a quick test), then the issue lies with YGG.

There are plenty of old issues regarding YGG, and they almost all come down to the same thing: their implementation of Cloudflare IAUM protection as a result of them being DDoS'd. There's nothing we can do about that.

If there's something there which doesn't apply to you, feel free to reopen and explain.

**Comment by Phantomouf** [comment]
Hi my friend, i just test torrentQQ and its not working too.
i get this error : 
 An error occurred while testing this indexer
Test search in TorrentQQ => Found no results while trying to browse this tracker

**Comment by ilike2burnthing** [comment]
That looks like a completely different issue. Enable enhanced logging in Jackett and see if that shed any more light as to what is being returned to TorrentQQ.
