### ISSUE TITLE
Flaresolverr failing with message firefox busy

### ISSUE THREAD

**Issue by t-zone** [FlareSolverr/FlareSolverr#706]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 2.2.10
- Last working FlareSolverr version: 2.2.10
- Operating system: Windows 10 Pro
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

I noticed that flaresolverr stopped working (which is normally auto launched with task scheduler) and when I try to open it manually it gets stuck on 'Testing web browser installation' and I only when I try to close the window I get an error message for a second before it closes (attached below). It was working fine on this version and suddenly stopped. I haven't installed version 3 as it requires installation from the source code which I don't have the technical understanding to do.

### Logged Error Messages

```text
https://0bin.net/paste/nrdc+837#fRisHYjBDsht7zGim1cI50meSaes1Vxa3jynG42rhqD
```

### Screenshots

https://0bin.net/paste/nrdc+837#fRisHYjBDsht7zGim1cI50meSaes1Vxa3jynG42rhqD

**Comment by DrStrange** [comment]
I'm not a dev but you can try this :
    Press windows key plus R on your keyboard to open the run command box and type this:
    resmon.exe
    click OK to open resource monitor
    In the resource monitor, navigate to CPU tab
    Under Associated Handles in the search box, copy the path to C:\Users\Tarik\AppData\Local  \Temp\puppeteer_dev_firefox_profile-Efv0dj\cookies.sqlite and paste it in there
    Click on the search icon
    You should be able to see all the programs using the cookies.sqlite
    Right-click each program and end each process using cookies.sqlite
    Close resource monitor
    Open Task Manager as an administrator
    End each process named FireFox Nightly
    Then see if you are allowed to delete C:\Users\Tarik\AppData\Local\Temp\puppeteer_dev_firefox_profile-Efv0dj.Also delete   any other C:\Users\Tarik\AppData\Local\Temp\puppeteer_dev_firefox_profile-****** folders that exist.
    Take a look at this issue: https://github.com/FlareSolverr/FlareSolverr/issues/703 The issue was resolved by setting the TEST_URL to www.reddit.com because flaresolverr is not connecting to www.google.com. That issue has a different error message than your error message but you could try it. How to use:
 1. Open a command prompt and navigate to C:\ProgramData\flaresolverr
 2. type TEST_URL=https://www.reddit.com
 3. type flaresolverr.exe

Does flaresolverr start now? 
If it doesn't, that is as much as I would know how to fix it.

**Comment by t-zone** [comment]
I ended the processes for cookies.sqlite in Resource Manager but there were no Task Manager entries FireFox Nightly. I deleted all the C:\Users\Tarik\AppData\Local\Temp\puppeteer_dev_firefox_profile- folders. The command TEST_URL=https://www.reddit.com/ didn't work for me while in the flaresolverr folder (not sure if I did it right, output below). I tried to start flaresolverr from cmd but it timed out (output below).

C:\Windows\system32>cd C:\ProgramData\flaresolverr

C:\ProgramData\flaresolverr>TEST_URL=https://www.reddit.com
'TEST_URL' is not recognized as an internal or external command,
operable program or batch file.

C:\ProgramData\flaresolverr>flaresolverr.exe
2023-02-20T16:48:57+00:00 INFO FlareSolverr v2.2.10
2023-02-20T16:48:57+00:00 INFO Testing web browser installation...
2023-02-20T16:49:39+00:00 ERROR TimeoutError: Navigation timeout of 40000 ms exceeded
    at C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:108:111

**Comment by DrStrange** [comment]
@t-zone 
You left out set
Open command prompt then navigate to Flaresolverr folder.
Then type:
set TEST_URL=https://www.reditt.com
then type:
flaresolverr.exe

**Comment by t-zone** [comment]
This worked and flaresolverr started, thanks! 

I believe it needs to be switched to this URL each time its launched? I normally have a task scheduled to trigger a bat file which silently launches flaresolverr (start /B "" "C:\ProgramData\flaresolverr\flaresolverr.exe"). Is there a way to integrate changing the test URL into this bat file?

**Comment by DrStrange** [comment]
Running `flaresolverr.exe /help` or `flaresolverr.exe /?` doesn't output any options so I imagine that TEST_URL=www.reddit.com could not be integrated into your scheduled task. You could try: in the scheduled task, in the  "Edit Action>Add Arguments (optional)" box type in TEST_URL=https://www.reddit.com and see does flaresolverr start. Before you do this, runTask Manager as an administrator and stop any instances of Firefox Nightly. If it doesn't work, then:
What does work instead of trying to change the scheduled task, is to add TEST_URL=www.reddit.com as an enivironmental value. Open a command prompt then type:
rundll32 sysdm.cpl,EditEnvironmentVariables
In the Environmental Variables window that opens, underneath the User variables for Tarik box click New then in the Variable name type:
TEST_URL
In the Variable value type:
https://www.reddit.com
and ok that and ok to close the Environmental Variables window.

**Comment by t-zone** [comment]
İ tried both methods, neither worked. I did this for the environmental variable but got the same error as before.

Open a command prompt then type:
rundll32 sysdm.cpl,EditEnvironmentVariables
In the Environmental Variables window that opens, underneath the User variables for Tarik box click New then in the Variable name type:
TEST_URL
In the Variable value type:
https://www.reddit.com/
and ok that and ok to close the Environmental Variables window.

**Comment by DrStrange** [comment]
This method seems to work:
End and disable your scheduled task.
Use task manager and end any instances of Flaresolverr.exe and Firefox Nightly. You may need to use Task Manager as an administrator to close some instances of Firefox Nightly.
Go to: 
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup
In this folder create a file called flaresolverr.txt (or whatever you want to call the file).
Open the file and type:
```
set TEST_URL=https://www.reddit.com
C:\ProgramData\Flaresolverr\flaresolverr.exe
```
Save and close the file then right click it and rename it flaresolverr.bat (or whatever you want to call it, as long as it is a .bat file)
To test it, open a command prompt, navigate to this folder and type:
`flaresolverr.bat`
If flaresolverr.exe runs then you can delete your scheduled task if you wish, as long as it is disabled.

**Comment by t-zone** [comment]
Creating the bat file with the text below worked:

cd C:\ProgramData\Flaresolverr\
set TEST_URL=https://www.reditt.com
flaresolverr.exe

Strangely, when it's 'reddit.com' (correct spelling) it didn't work but with the typo 'reditt.com' it worked even though its not a legit site.

I also didnt use the startup folder because it keeps the cmd window open. I kept the bat file in the flaresolverr folder and used task scheduler with options “Run whether user is logged on or not“& “Do not store password” as this keeps the cmd window hidden.

Thanks @DrStrange for helping resolve the issue, much appreciated.

**Comment by DrStrange** [comment]
@t-zone,
Glad to see you got it solved. I didn't think to use a .bat file as a scheduled task and would never have thought to try reditt.com. 
I did try putting a .bat file in the startup folder but that gave me an error. I couldn't see the output error as the command prompt window closed too quickly. I tried using a command redirection operator to send the output to a text file so I could see what the error was but no .txt file was created. It seemed that the error was that TEST_URL=https://www.reditt.com was not being passed to flaresolverr.exe. I did run the .bat file that I had in startup and flaresolverr ran as normal with no errors.
I tried your scheduled task method. I found that only "Run whether user is logged on or not" needs checked to keep the cmd window hidden.  "Do not store password" does not need checked.
Using Scheduled tasks is quicker than using startup for troubleshooting because you can stop and start the task immediately instead of waiting for the PC to log off/on when using startup.
