### ISSUE TITLE
FlareSolverr binary with fixed location

### ISSUE THREAD

**Issue by ngosang** [FlareSolverr/FlareSolverr#741]
### Discussed in https://github.com/FlareSolverr/FlareSolverr/discussions/740

<div type='discussions-op-text'>

<sup>Originally posted by **Linouxs** March 21, 2023</sup>
Hi, Love it that the binary for Windows is added in the latest update. I would like to run FlareSolverr through the same vpn as Prowlarr (at the same pc) with split tunneling. But the problem is that I can't add the executable from Chromium to the vpn (C:\users\user\appdata\local\temp\\...\chrome.exe) because the location of the executable changes sometimes. I can't disable split tunneling because Plex and other services are running at the same device. Would it be possible to use a fixed location for the Chromium executable?</div>

**Comment by Linouxs** [comment]
> @Linouxs yes, I will add it in the next release.

Awesome, thanks!

**Comment by ngosang** [comment]
https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.1.1
e0bf02fb8b24865cf9450637baaa1a7845093b34

@txtsd Sorry, you will have to change the binary package for Arch. This will be the last time, I promise :)

**Comment by txtsd** [comment]
@ngosang Don't worry about it lol. I package flaresolverr because it's important to me. I'm not gonna be annoyed by upstream changes. Thank you for your work and dedication. I've been following your work since your [qbittorrent search plugins](https://github.com/qbittorrent/search-plugins) days when I was just a FOSS fledgling.
