### ISSUE TITLE
[yggtorrent] FlareSolverr was unable to process the request. Message: Error: Error solving the challenge. Message: unknown error: session deleted because of page crash\nfrom

### ISSUE THREAD

**Issue by neofleo** [FlareSolverr/FlareSolverr#929]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.6
- Last working FlareSolverr version: I don't know
- Operating system: Ubuntu
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
- Are you using a VPN: [yes/no] no
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one: no
- URL to test this issue: can't send my flaresolverr url
```

### Description

Using flaresolverr for Jackett and Prowlarr, was working fine till some days now.
Reinstalled Flaresolverr on wto different machines on different network but still the same problem connecting to YGGTorrent & YGGCookie, got the same error.

### Logged Error Messages

```text
An error occurred while updating this indexer
FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Message: unknown error: session deleted because of page crash\nfrom unknown error: cannot determine loading status\nfrom tab crashed\n (Session info: chrome=116.0.5845.180)\nStacktrace:\n#0 0x560a57ddb023 <unknown>\n#1 0x560a57af76ec <unknown>\n#2 0x560a57ae01ce <unknown>\n#3 0x560a57adecdb <unknown>\n#4 0x560a57adf2fd <unknown>\n#5 0x560a57af3a53 <unknown>\n#6 0x560a57af4a32 <unknown>\n#7 0x560a57b01faf <unknown>\n#8 0x560a57b05f31 <unknown>\n#9 0x560a57adf8c7 <unknown>\n#10 0x560a57b01c64 <unknown>\n#11 0x560a57b779bb <unknown>\n#12 0x560a57b5fbb3 <unknown>\n#13 0x560a57b2a9de <unknown>\n#14 0x560a57b2bd72 <unknown>\n#15 0x560a57da9fb6 <unknown>\n#16 0x560a57dad02d <unknown>\n#17 0x560a57dacac6 <unknown>\n#18 0x560a57dad4d5 <unknown>\n#19 0x560a57db390b <unknown>\n#20 0x560a57dad856 <unknown>\n#21 0x560a57d86b0d <unknown>\n#22 0x560a57dc6265 <unknown>\n#23 0x560a57dc645f <unknown>\n#24 0x560a57dd404f <unknown>\n#25 0x7f47a15bbea7 start_thread\n
```

**Comment by lemystere** [comment]
Same error here, I add the debug log with LOG_LEVEL=debug :

`Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.wtf/engine/search?category=2145&do=search&order=asc&sort=seed', 'proxy': {}}
Launching web browser...
Started executable: `/app/chromedriver` in a child process with pid: 341
New instance of webdriver has been created to perform the request
Navigating to... https://www3.yggtorrent.wtf/engine/search?category=2145&do=search&order=asc&sort=seed
Challenge detected. Title found: Just a moment...
Waiting for title (attempt 1): Just a moment...
Timeout waiting for selector
Try to find the Cloudflare verify checkbox...
Cloudflare verify checkbox not found on the page.
Try to find the Cloudflare 'Verify you are human' button...
The Cloudflare 'Verify you are human' button not found on the page.
Waiting for title (attempt 2): Just a moment...
Waiting for title (attempt 2): DDoS-Guard
Waiting for selector (attempt 2): #cf-challenge-running
Waiting for selector (attempt 2): .ray_id
Waiting for selector (attempt 2): .attack-box
Waiting for selector (attempt 2): #cf-please-wait
Waiting for selector (attempt 2): #challenge-spinner
Waiting for selector (attempt 2): #trk_jschal_js
Waiting for selector (attempt 2): td.info #js_info
Waiting for selector (attempt 2): div.vc div.text-box h2
Waiting for redirect
Timeout waiting for redirect
Challenge solved!
A used instance of webdriver has been destroyed
Error: Error solving the challenge. Message: unknown error: session deleted because of page crash\nfrom unknown error: cannot determine loading status\nfrom tab crashed\n  (Session info: chrome=116.0.5845.180)\nStacktrace:\n#0 0x5626a7bbd023 <unknown>\n#1 0x5626a78d96ec <unknown>\n#2 0x5626a78c21ce <unknown>\n#3 0x5626a78c0cdb <unknown>\n#4 0x5626a78c12fd <unknown>\n#5 0x5626a78d5a53 <unknown>\n#6 0x5626a78d6a32 <unknown>\n#7 0x5626a78e3faf <unknown>\n#8 0x5626a78e7f31 <unknown>\n#9 0x5626a78c18c7 <unknown>\n#10 0x5626a78e3c64 <unknown>\n#11 0x5626a79599bb <unknown>\n#12 0x5626a7941bb3 <unknown>\n#13 0x5626a790c9de <unknown>\n#14 0x5626a790dd72 <unknown>\n#15 0x5626a7b8bfb6 <unknown>\n#16 0x5626a7b8f02d <unknown>\n#17 0x5626a7b8eac6 <unknown>\n#18 0x5626a7b8f4d5 <unknown>\n#19 0x5626a7b9590b <unknown>\n#20 0x5626a7b8f856 <unknown>\n#21 0x5626a7b68b0d <unknown>\n#22 0x5626a7ba8265 <unknown>\n#23 0x5626a7ba845f <unknown>\n#24 0x5626a7bb604f <unknown>\n#25 0x7fab439e7ea7 start_thread\n
Response => POST /v1 body: {'status': 'error', 'message': 'Error: Error solving the challenge. Message: unknown error: session deleted because of page crash\\nfrom unknown error: cannot determine loading status\\nfrom tab crashed\\n  (Session info: chrome=116.0.5845.180)\\nStacktrace:\\n#0 0x5626a7bbd023 <unknown>\\n#1 0x5626a78d96ec <unknown>\\n#2 0x5626a78c21ce <unknown>\\n#3 0x5626a78c0cdb <unknown>\\n#4 0x5626a78c12fd <unknown>\\n#5 0x5626a78d5a53 <unknown>\\n#6 0x5626a78d6a32 <unknown>\\n#7 0x5626a78e3faf <unknown>\\n#8 0x5626a78e7f31 <unknown>\\n#9 0x5626a78c18c7 <unknown>\\n#10 0x5626a78e3c64 <unknown>\\n#11 0x5626a79599bb <unknown>\\n#12 0x5626a7941bb3 <unknown>\\n#13 0x5626a790c9de <unknown>\\n#14 0x5626a790dd72 <unknown>\\n#15 0x5626a7b8bfb6 <unknown>\\n#16 0x5626a7b8f02d <unknown>\\n#17 0x5626a7b8eac6 <unknown>\\n#18 0x5626a7b8f4d5 <unknown>\\n#19 0x5626a7b9590b <unknown>\\n#20 0x5626a7b8f856 <unknown>\\n#21 0x5626a7b68b0d <unknown>\\n#22 0x5626a7ba8265 <unknown>\\n#23 0x5626a7ba845f <unknown>\\n#24 0x5626a7bb604f <unknown>\\n#25 0x7fab439e7ea7 start_thread\\n', 'startTimestamp': 1698090208573, 'endTimestamp': 1698090213997, 'version': '3.3.6'}
Response in 5.424 s
127.0.0.1 POST http://localhost:8191/v1 500 Internal Server Error`

**Comment by lemystere** [comment]
Same error here, I add my debug log : 

> Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.wtf/engine/search?category=2145&do=search&order=asc&sort=seed', 'proxy': {}}
Launching web browser...
Started executable: `/app/chromedriver` in a child process with pid: 341
New instance of webdriver has been created to perform the request
Navigating to... https://www3.yggtorrent.wtf/engine/search?category=2145&do=search&order=asc&sort=seed
Challenge detected. Title found: Just a moment...
Waiting for title (attempt 1): Just a moment...
Timeout waiting for selector
Try to find the Cloudflare verify checkbox...
Cloudflare verify checkbox not found on the page.
Try to find the Cloudflare 'Verify you are human' button...
The Cloudflare 'Verify you are human' button not found on the page.
Waiting for title (attempt 2): Just a moment...
Waiting for title (attempt 2): DDoS-Guard
Waiting for selector (attempt 2): #cf-challenge-running
Waiting for selector (attempt 2): .ray_id
Waiting for selector (attempt 2): .attack-box
Waiting for selector (attempt 2): #cf-please-wait
Waiting for selector (attempt 2): #challenge-spinner
Waiting for selector (attempt 2): #trk_jschal_js
Waiting for selector (attempt 2): td.info #js_info
Waiting for selector (attempt 2): div.vc div.text-box h2
Waiting for redirect
Timeout waiting for redirect
Challenge solved!
A used instance of webdriver has been destroyed
Error: Error solving the challenge. Message: unknown error: session deleted because of page crash\nfrom unknown error: cannot determine loading status\nfrom tab crashed\n  (Session info: chrome=116.0.5845.180)\nStacktrace:\n#0 0x5626a7bbd023 <unknown>\n#1 0x5626a78d96ec <unknown>\n#2 0x5626a78c21ce <unknown>\n#3 0x5626a78c0cdb <unknown>\n#4 0x5626a78c12fd <unknown>\n#5 0x5626a78d5a53 <unknown>\n#6 0x5626a78d6a32 <unknown>\n#7 0x5626a78e3faf <unknown>\n#8 0x5626a78e7f31 <unknown>\n#9 0x5626a78c18c7 <unknown>\n#10 0x5626a78e3c64 <unknown>\n#11 0x5626a79599bb <unknown>\n#12 0x5626a7941bb3 <unknown>\n#13 0x5626a790c9de <unknown>\n#14 0x5626a790dd72 <unknown>\n#15 0x5626a7b8bfb6 <unknown>\n#16 0x5626a7b8f02d <unknown>\n#17 0x5626a7b8eac6 <unknown>\n#18 0x5626a7b8f4d5 <unknown>\n#19 0x5626a7b9590b <unknown>\n#20 0x5626a7b8f856 <unknown>\n#21 0x5626a7b68b0d <unknown>\n#22 0x5626a7ba8265 <unknown>\n#23 0x5626a7ba845f <unknown>\n#24 0x5626a7bb604f <unknown>\n#25 0x7fab439e7ea7 start_thread\n
Response => POST /v1 body: {'status': 'error', 'message': 'Error: Error solving the challenge. Message: unknown error: session deleted because of page crash\\nfrom unknown error: cannot determine loading status\\nfrom tab crashed\\n  (Session info: chrome=116.0.5845.180)\\nStacktrace:\\n#0 0x5626a7bbd023 <unknown>\\n#1 0x5626a78d96ec <unknown>\\n#2 0x5626a78c21ce <unknown>\\n#3 0x5626a78c0cdb <unknown>\\n#4 0x5626a78c12fd <unknown>\\n#5 0x5626a78d5a53 <unknown>\\n#6 0x5626a78d6a32 <unknown>\\n#7 0x5626a78e3faf <unknown>\\n#8 0x5626a78e7f31 <unknown>\\n#9 0x5626a78c18c7 <unknown>\\n#10 0x5626a78e3c64 <unknown>\\n#11 0x5626a79599bb <unknown>\\n#12 0x5626a7941bb3 <unknown>\\n#13 0x5626a790c9de <unknown>\\n#14 0x5626a790dd72 <unknown>\\n#15 0x5626a7b8bfb6 <unknown>\\n#16 0x5626a7b8f02d <unknown>\\n#17 0x5626a7b8eac6 <unknown>\\n#18 0x5626a7b8f4d5 <unknown>\\n#19 0x5626a7b9590b <unknown>\\n#20 0x5626a7b8f856 <unknown>\\n#21 0x5626a7b68b0d <unknown>\\n#22 0x5626a7ba8265 <unknown>\\n#23 0x5626a7ba845f <unknown>\\n#24 0x5626a7bb604f <unknown>\\n#25 0x7fab439e7ea7 start_thread\\n', 'startTimestamp': 1698090208573, 'endTimestamp': 1698090213997, 'version': '3.3.6'}
Response in 5.424 s
127.0.0.1 POST http://localhost:8191/v1 500 Internal Server Error

**Comment by Brokeos** [comment]
I had the same error and upgraded to version 3.3.2, and it's been working perfectly ever since.

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/880
